### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by Mariana041** [syl3n7/CatchMeIfYouCan#26]

**Comment by syl3n7** [comment]
![Image](https://user-images.githubusercontent.com/3891084/170894366-d2539750-e5b5-415a-8c18-6277d4b6fd48.png)

**Comment by syl3n7** [comment]
@Mariana041 did this 


![Image](https://user-images.githubusercontent.com/3891084/171999746-08e51b2b-b965-457f-9771-e3816ed8cc98.png)

this version has a more natural feel to the direction the arrow is pointing, similar to the windows cursor.

**Comment by Mariana041** [comment]
Outras opções de cursor: 

![Image](https://user-images.githubusercontent.com/100358775/172056045-5289162b-7124-480b-8bf6-bc61158c1263.png)



![Image](https://user-images.githubusercontent.com/100358775/172056046-1d8736a1-7034-4329-8596-e12ebcc43d92.png)



![Image](https://user-images.githubusercontent.com/100358775/172056051-d4ba3fe9-2fb1-4f19-97ba-6db60096b0b8.png)

Por nao gostar de como ficou o cursor no jogo, decidi criar outro design. E ficou como cursor final este último.
